<center><b>In the name of God</b></center>

<b>Course</b>: Machine Learning
<br>
<b>Description:</b> HomeWork 2 | Question 3
<br>
<b>Developer</b>: Alireza Mazochi (400131075)

# Libraries

In [50]:
# Import Allowed Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load and Overview

In [60]:
data = pd.read_csv("iris.data", header=None, names=["Sepal Length", "Sepal Width", "Petal Length", "Petal Width", "Class"])

In [61]:
data

     Sepal Length  Sepal Width  Petal Length  Petal Width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

# Shuffle

In [62]:
if True:
    # Shuffling one time and save it 
    data = data.sample(frac=1)
    
    for i, item in data.iterrows():
        data.at[i, "Fold"] = int(i/15) 
    
    data.to_csv("iris_shuffled.csv")
else:
    # Load shuffled data
    data = pd.read_csv("iris_shuffled.csv")#.drop(columns = ["Unnamed: 0"])

In [63]:
data

,Sepal Length,Sepal Width,Petal Length,Petal Width,Class,Fold
61,5.9,3.0,4.2,1.5,Iris-versicolor,4.0
67,5.8,2.7,4.1,1.0,Iris-versicolor,4.0
118,7.7,2.6,6.9,2.3,Iris-virginica,7.0
92,5.8,2.6,4.0,1.2,Iris-versicolor,6.0
139,6.9,3.1,5.4,2.1,Iris-virginica,9.0
...,...,...,...,...,...,...
73,6.1,2.8,4.7,1.2,Iris-versicolor,4.0
33,5.5,4.2,1.4,0.2,Iris-setosa,2.0
135,7.7,3.0,6.1,2.3,Iris-virginica,9.0
114,5.8,2.8,5.1,2.4,Iris-virginica,7.0
140,6.7,3.1,5.6,2.4,Iris-virginica,9.0

In [64]:
data.sort_values("Fold")

,Sepal Length,Sepal Width,Petal Length,Petal Width,Class,Fold
14,5.8,4.0,1.2,0.2,Iris-setosa,0.0
12,4.8,3.0,1.4,0.1,Iris-setosa,0.0
7,5.0,3.4,1.5,0.2,Iris-setosa,0.0
13,4.3,3.0,1.1,0.1,Iris-setosa,0.0
11,4.8,3.4,1.6,0.2,Iris-setosa,0.0
...,...,...,...,...,...,...
143,6.8,3.2,5.9,2.3,Iris-virginica,9.0
141,6.9,3.1,5.1,2.3,Iris-virginica,9.0
147,6.5,3.0,5.2,2.0,Iris-virginica,9.0
145,6.7,3.0,5.2,2.3,Iris-virginica,9.0
140,6.7,3.1,5.6,2.4,Iris-virginica,9.0